#!/usr/bin/env bash
#@ * * * * *

#This is a simple sh-at scheduled job example, it just hits the local
#service -- which is on the container itself and so isn't at /echo

echo Goodbye $(pwd) ${PORT}
curl http://localhost/goodbye
